version: 0.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG: C:\vcpkg
install:
- cmd: install.bat
build_script:
- cmd: >-
    build.bat x86

    build.bat x64

    package.bat

artifacts:
- path: artifacts\openrct2-libs-vs2017.zip
  name: OpenRCT2
