version: 0.1.0.{build}
os: Visual Studio 2017
environment:
  PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64;$(PATH)
  VCPKG: C:\vcpkg
install:
- cmd: install.bat
build_script:
- cmd: >-
    build.bat x86

    build.bat x64

    package.bat

artifacts:
- path: artifacts\openrct2-libs-vs2017.zip
  name: OpenRCT2
