name: CI
on: 
  push:
    branches:
      '**'
    tags:
      - '!v**'
  pull_request:
env:
  version: xx
  VCPKG_COMMIT_HASH: 401b26c9866a071f645ae57831caa419b2c48be1
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - triplet: x86-windows-static
            vcpkgPackages: 'benchmark breakpad discord-rpc duktape freetype fribidi gtest libpng libzip[core] nlohmann-json sdl2 speexdsp zlib'
          - triplet: x64-windows-static
            vcpkgPackages: 'benchmark breakpad discord-rpc duktape freetype fribidi gtest libpng libzip[core] nlohmann-json sdl2 speexdsp zlib'
          - triplet: arm64-windows-static
            # fribidi is disabled due to https://github.com/microsoft/vcpkg/issues/11248 [fribidi] Fribidi doesn't cross-compile on x86-64 to target arm/arm64
            vcpkgPackages: 'discord-rpc duktape freetype gtest libpng libzip[core] nlohmann-json sdl2 speexdsp zlib'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          vcpkgGitCommitId: '${{ env.VCPKG_COMMIT_HASH }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
      - name: Zip stuff
        run: |
          pushd ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}\\installed\\${{ matrix.triplet }}
          7z a -tzip -mx9 -mtc=off ..\openrct2-libs-v${{ env.version }}-${{ matrix.triplet }}.zip "*"
          popd
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: openrct2-libs-v${{ env.version }}-${{ matrix.triplet }}.zip
          path: ${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}\\installed\\openrct2-libs-v${{ env.version }}-${{ matrix.triplet }}.zip
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg and packages
        id: macos_build
        shell: bash
        run: |
          export VCPKG_COMMIT_HASH='${{ env.VCPKG_COMMIT_HASH }}'
          ./macos_build.sh
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v2
        with:
          name: openrct2-libs-v${{ env.version }}-x64-macos-dylibs.zip
          path: openrct2-libs-v${{ env.version }}-x64-macos-dylibs.zip
